# Generated by Django 3.2 on 2021-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('price', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Complete Price',
                'verbose_name_plural': 'Complete Prices',
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
