# Generated by Django 3.2.3 on 2021-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_complete_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='price',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='complete',
            name='pub_date',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
