# Generated by Django 3.2.3 on 2021-06-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210619_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='complete',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
