# Generated by Django 3.2.3 on 2021-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210701_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='url',
            field=models.URLField(default=0, verbose_name='url'),
            preserve_default=False,
        ),
    ]
